import { chromium, expect } from '@playwright/test';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = []; page.on('pageerror', e => errors.push(e.message));
await page.goto('http://localhost:5188/', { waitUntil: 'networkidle' });
await page.locator('#boot').waitFor({ state: 'hidden' });
await page.getByRole('button', { name: 'STEP ON THE MAT' }).click();
await page.getByRole('button', { name: 'Skip introductions' }).click();
// Fixture setup changes only the time, score and toss; production UI drives transitions.
await page.evaluate(() => { const m = window.__VARSITY__.match; m.state.firstChoice = 0; m.state.secondChoice = 1; m.state.remaining = 0.03; });
await page.locator('#break').waitFor({ state: 'visible' });
await expect(page.locator('#break-title')).toHaveText('YOUR CHOICE.');
await page.screenshot({ path: 'test-results/period-choice.png' });
await page.locator('[data-choice="defer"]').click();
await expect(page.locator('#break-title')).toHaveText('THEIR CHOICE.');
await page.waitForFunction(() => window.__VARSITY__.match.state.phase === 'wrestling');
await page.evaluate(() => { window.__VARSITY__.match.state.restartTime = 0; window.__VARSITY__.match.state.remaining = 0.03; });
await page.locator('#break').waitFor({ state: 'visible' });
await expect(page.locator('#break-title')).toHaveText('YOUR CHOICE.');
await page.locator('[data-choice="bottom"]').click();
await page.waitForFunction(() => window.__VARSITY__.match.state.phase === 'wrestling');
console.log('Period choices, deferral and referee-position restart passed.');
await page.evaluate(() => { const m = window.__VARSITY__.match; m.state.restartTime = 0; m.state.remaining = 0.03; m.state.score = [3, 3]; m.state.riding = [0, 0]; });
await page.locator('#break').waitFor({ state: 'visible' });
await expect(page.locator('#break-title')).toHaveText('OVERTIME.');
await page.waitForFunction(() => window.__VARSITY__.match.state.phase === 'wrestling');
await expect(page.locator('#period')).toHaveText('SV 1');
const alpha = await page.evaluate(() => window.__VARSITY__.arena.camera.alpha);
await page.keyboard.press('KeyQ'); await page.waitForTimeout(1500);
const moved = await page.evaluate(() => window.__VARSITY__.arena.camera.alpha);
if (Math.abs(alpha - moved) < 0.4) throw new Error('Orbit camera did not respond');
await page.keyboard.press('KeyC'); await page.waitForTimeout(1500);
const beta = await page.evaluate(() => window.__VARSITY__.arena.camera.beta);
if (beta > 0.92) throw new Error('Wide camera did not respond');
console.log('Sudden victory, orbit and wide camera passed.');
await page.keyboard.press('Escape');
const t0 = await page.evaluate(() => window.__VARSITY__.match.state.remaining); await page.waitForTimeout(300);
const t1 = await page.evaluate(() => window.__VARSITY__.match.state.remaining);
if (t0 !== t1) throw new Error('Pause did not freeze clock');
await page.getByRole('button', { name: 'Graphics: HIGH' }).click();
await expect(page.locator('#quality')).toHaveText('Graphics: BALANCED');
await page.getByRole('button', { name: 'BACK TO THE MATCH' }).click();
console.log('Pause, resume and graphics settings passed.');
await page.close();

const mobileContext = await browser.newContext({ viewport: { width: 844, height: 390 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
const mobile = await mobileContext.newPage(); mobile.on('pageerror', e => errors.push(e.message));
await mobile.goto('http://localhost:5188/', { waitUntil: 'networkidle' }); await mobile.locator('#boot').waitFor({ state: 'hidden' });
await mobile.screenshot({ path: 'test-results/mobile-menu.png' });
await mobile.getByRole('button', { name: 'STEP ON THE MAT' }).tap();
await mobile.getByRole('button', { name: 'Skip introductions' }).tap();
await expect(mobile.locator('#joystick')).toBeVisible();
await expect(mobile.locator('#touch-primary')).toBeVisible();
await mobile.locator('#touch-setup').tap();
await mobile.screenshot({ path: 'test-results/mobile-match.png' });
const stick = await mobile.locator('#joystick').boundingBox();
const before = await mobile.evaluate(() => window.__VARSITY__.match.state.wrestlers[0].x);
await mobile.mouse.move(stick.x + stick.width / 2, stick.y + stick.height / 2); await mobile.mouse.down();
await mobile.mouse.move(stick.x + stick.width - 5, stick.y + stick.height / 2); await mobile.waitForTimeout(450); await mobile.mouse.up();
const after = await mobile.evaluate(() => window.__VARSITY__.match.state.wrestlers[0].x);
if (after - before < 0.1) throw new Error('Touch joystick did not move wrestler');
await mobile.setViewportSize({ width: 390, height: 844 }); await mobile.waitForTimeout(400); await mobile.screenshot({ path: 'test-results/mobile-portrait.png' });
const overflow = await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth);
if (overflow) throw new Error('Mobile viewport has horizontal overflow');
console.log('Mobile landscape, touch buttons, joystick and portrait layout passed. ERRORS', JSON.stringify(errors));
if (errors.length) throw new Error(errors.join('\n'));
await browser.close();
