import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';

await mkdir('test-results', { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true, args: ['--disable-background-timer-throttling'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', e => { if (e.type() === 'error') errors.push(e.text()); });
await page.goto('http://localhost:5188/', { waitUntil: 'networkidle' });
await page.locator('#boot').waitFor({ state: 'hidden', timeout: 60000 });
await page.waitForTimeout(2500);
await page.screenshot({ path: 'test-results/menu.png' });
console.log('MENU', await page.evaluate(() => ({ meshes: window.__VARSITY__.arena.scene.meshes.length, fps: window.__VARSITY__.arena.engine.getFps(), phase: window.__VARSITY__.match.state.phase })));
await page.getByRole('button', { name: 'STEP ON THE MAT' }).click();
await page.waitForTimeout(2000);
await page.screenshot({ path: 'test-results/intro.png' });
await page.getByRole('button', { name: 'Skip introductions' }).click();
await page.waitForTimeout(1500);
await page.screenshot({ path: 'test-results/match.png' });
console.log('MATCH', await page.evaluate(() => ({ fps: window.__VARSITY__.arena.engine.getFps(), phase: window.__VARSITY__.match.state.phase, score: window.__VARSITY__.match.state.score })));
await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Controls & rules' }).click();
await page.screenshot({ path: 'test-results/controls.png' });
await page.getByRole('button', { name: 'Close controls' }).click();
await page.getByRole('button', { name: 'BACK TO THE MATCH' }).click();
await page.evaluate(() => { const g = window.__VARSITY__; g.match.state.wrestlers[0].setup = 1; g.match.state.wrestlers[0].x = -0.7; g.match.state.wrestlers[1].x = 0.7; g.match.state.wrestlers[0].z = g.match.state.wrestlers[1].z = 0; });
await page.keyboard.press('KeyJ');
await page.waitForTimeout(2100);
await page.screenshot({ path: 'test-results/ground.png' });
console.log('GROUND', await page.evaluate(() => ({ top: window.__VARSITY__.match.state.top, score: window.__VARSITY__.match.state.score, events: window.__VARSITY__.match.state.events.slice(-3) })));
console.log('ERRORS', JSON.stringify(errors));
await browser.close();
