import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto('http://127.0.0.1:5188/');
await page.locator('#boot').waitFor({state:'hidden',timeout:60000});
await page.getByRole('button',{name:'STEP ON THE MAT'}).click();
await page.getByRole('button',{name:'Skip introductions'}).click();
await page.evaluate(() => {
  const {match:m}=window.__VARSITY__;
  m.opponent={reset(){},decide(){return {x:0,z:0,primary:false,secondary:false,setup:false,defend:false,sprint:false,primaryHeld:false};}};
  m.state.wrestlers[0].x=-0.76;m.state.wrestlers[1].x=0.76;
});
await page.waitForTimeout(600);
await page.locator('#action-setup').click();
await page.waitForTimeout(220);
assert.equal(await page.locator('#action-setup').evaluate(e=>e.classList.contains('executing')),true);
await page.screenshot({path:'test-results/player-handfight.png'});
await page.waitForTimeout(500);
await page.keyboard.press('KeyL');
await page.waitForTimeout(500);
// J arrives during the final recovery window and should be buffered.
await page.keyboard.press('KeyJ');
await page.waitForTimeout(500);
await page.screenshot({path:'test-results/player-shot.png'});
await page.waitForTimeout(1600);
assert.equal(await page.evaluate(()=>window.__VARSITY__.match.state.top),0);
assert.match(await page.locator('#position-name').innerText(),/TOP/);
await page.screenshot({path:'test-results/player-ride.png'});
await page.keyboard.press('KeyK');await page.waitForTimeout(350);
await page.screenshot({path:'test-results/player-breakdown.png'});
await page.evaluate(()=>{const m=window.__VARSITY__.match;m.state.control=97;m.state.wrestlers[0].cooldown=0;});
await page.keyboard.down('KeyJ');await page.waitForTimeout(700);
assert.match(await page.locator('#primary-label').innerText(),/PRESSURE/);
await page.screenshot({path:'test-results/player-pin.png'});
await page.keyboard.up('KeyJ');
await page.evaluate(()=>{const m=window.__VARSITY__.match;m.state.exposure=0;m.setGround(1);m.state.wrestlers[0].cooldown=0;});
await page.keyboard.press('KeyL');await page.waitForTimeout(330);
assert.equal(await page.evaluate(()=>window.__VARSITY__.match.state.wrestlers[0].move),'heist');
await page.screenshot({path:'test-results/player-heist.png'});
console.log('PLAYER QA', JSON.stringify({errors,position:await page.locator('#position-name').innerText(),fps:await page.evaluate(()=>window.__VARSITY__.arena.engine.getFps())}));
assert.deepEqual(errors,[]);
await browser.close();
