import { chromium, expect } from '@playwright/test';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [], external = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', e => { if (e.type() === 'error') errors.push(e.text()); });
page.on('request', r => { if (!r.url().startsWith('http://127.0.0.1:5190/') && !r.url().startsWith('data:') && !r.url().startsWith('blob:')) external.push(r.url()); });
await page.goto('http://127.0.0.1:5190/', { waitUntil: 'networkidle' });
await page.locator('#boot').waitFor({ state: 'hidden' });
if (await page.evaluate(() => !!window.__VARSITY__)) throw new Error('Debug hook leaked into production');
await page.getByRole('button', { name: 'STEP ON THE MAT' }).click();
await page.getByRole('button', { name: 'Skip introductions' }).click();
await page.keyboard.down('KeyD'); await page.waitForTimeout(450); await page.keyboard.up('KeyD');
await page.keyboard.press('KeyL'); await page.waitForTimeout(800); await page.keyboard.press('KeyL'); await page.waitForTimeout(800); await page.keyboard.press('KeyJ');
await page.waitForTimeout(1900); await page.screenshot({ path: 'test-results/production-match.png' });
await page.keyboard.press('Escape'); await expect(page.locator('#paused')).toBeVisible();
await page.getByRole('button', { name: 'Return to locker room' }).click(); await expect(page.locator('#menu')).toBeVisible();
console.log('PRODUCTION', JSON.stringify({ title: await page.title(), errors, externalRequests: external, debugHookRemoved: true }));
if (errors.length || external.length) throw new Error('Production smoke failed');
await browser.close();
