/** Career awards are independent of NCAA placements (including cancelled 2020). */
const pastHodge = 'https://ohiostatebuckeyes.com/news/2015/3/30/stieber-wins-2015-dan-hodge-trophy';
export const HODGE_AWARDS: Record<string, { years: number[]; source: string }> = {
  'T.J. Jaworsky': { years: [1995], source: pastHodge },
  'Les Gutches': { years: [1996], source: pastHodge },
  'Kerry McCoy': { years: [1997], source: pastHodge },
  'Mark Ironside': { years: [1998], source: pastHodge },
  'Stephen Neal': { years: [1999], source: pastHodge },
  'Cael Sanderson': { years: [2000, 2001, 2002], source: pastHodge },
  'Nick Ackerman': { years: [2001], source: pastHodge },
  'Eric Larkin': { years: [2003], source: pastHodge },
  'Emmett Willson': { years: [2004], source: pastHodge },
  'Steve Mocco': { years: [2005], source: pastHodge },
  'Ben Askren': { years: [2006, 2007], source: pastHodge },
  'Brent Metcalf': { years: [2008], source: pastHodge },
  'Jake Herbert': { years: [2009], source: pastHodge },
  'Jayson Ness': { years: [2010], source: pastHodge },
  'Jordan Burroughs': { years: [2011], source: pastHodge },
  'David Taylor': { years: [2012, 2014], source: pastHodge },
  'Kyle Dake': { years: [2013], source: pastHodge },
  'Logan Stieber': { years: [2015], source: pastHodge },
  'Alex Dieringer': { years: [2016], source: 'https://okstate.com/news/2016/3/28/wrestling-alex-dieringer-wins-2016-hodge-trophy?path=mbball' },
  'Zain Retherford': { years: [2017, 2018], source: 'https://gopsusports.com/news/2018/03/26/wr-zain-wins-the-hodge-again' },
  'Bo Nickal': { years: [2019], source: 'https://gopsusports.com/news/2019/04/1/bo-nickal-wins-the-hodge' },
  'Spencer Lee': { years: [2020, 2021], source: 'https://hawkeyesports.com/news/2021/03/29/spencer-lee-wins-dan-hodge-trophy-2' },
  'Gable Steveson': { years: [2021, 2022], source: 'https://gophersports.com/sports/wrestling/roster/gable-steveson/22871' },
  'Mason Parris': { years: [2023], source: 'https://mgoblue.com/news/2023/3/27/wrestling-parris-wins-prestigious-dan-hodge-trophy' },
  'Aaron Brooks': { years: [2024], source: 'https://gopsusports.com/news/2024/04/1/nittany-lion-aaron-brooks-wins-2024-hodge-trophy-as-nations-top-collegiate-wrestler' },
  'Wyatt Hendrickson': { years: [2025], source: 'https://goairforcefalcons.com/news/2025/3/31/wrestling-wyatt-hendrickson-wins-dan-hodge-trophy' },
  'Mitchell Mesenbrink': { years: [2026], source: 'https://gopsusports.com/news/2026/03/30/mitchell-mesenbrink-wins-2026-hodge-trophy-as-nations-top-collegiate-wrestler' },
};

export interface PinHistory { falls?: number; bouts?: number; gorriaranYears?: number[]; source: string; gorriaranSource?: string }
export const PIN_HISTORY: Record<string, PinHistory> = {
  'Nick Simmons': {falls:46,bouts:158,source:'https://msuspartans.com/honors/hall-of-fame/nick-simmons/193'},
  'Randy Lewis': {falls:64,bouts:139,source:'https://hawkeyesports.com/news/2004/06/16/four-time-all-americans'},
  'Jeff Smith': {falls:23,bouts:52,source:'https://s3.us-east-2.amazonaws.com/sidearm.nextgen.sites/msuspartans.com/documents/2015/10/30/_msu_m_wrestl_2015_16_misc_non_event__RecordBook.pdf#page=6'},
  'Wyatt Hendrickson': {falls:72,bouts:138,gorriaranYears:[2023],source:'https://okstate.com/sports/wrestling/roster/wyatt-hendrickson/12920'},
  "Jason Powell": {gorriaranYears:[2003],source:"https://huskers.com/sports/wrestling/roster/season/2001-02/player/jason-powell"},
  "Tolly Thompson": {falls:53,bouts:178,source:"https://s3.us-east-2.amazonaws.com/sidearm.nextgen.sites/huskers.com/documents/2019/8/30/2019_20_Nebraska_All_Sport_Record_Book.pdf#page=298"},
  "Chris Taylor": {falls:70,bouts:88,gorriaranYears:[1973],gorriaranSource:"https://nwhof.org/brackets/43#page=1",source:"https://cyclones.com/news/2012/5/31/205435327"},
  "Carl Adams": {falls:20,bouts:90,source:"https://nwhof.org/hall_of_fame/bio/4679"},
  "Jessie Whitmer": {falls:13,bouts:70,source:"https://nwhof.org/national-wrestling-hall-of-fame/champions-database?tab=ncaa&wrestler=6308"},
  "Terry Steiner": {falls:25,bouts:149,source:"https://nwhof.org/national-wrestling-hall-of-fame/bio/12735"},
  "T.J. Williams": {falls:12,bouts:99,source:"https://nwhof.org/national-wrestling-hall-of-fame/champions-database?tab=ncaa&wrestler=12525"},
  "Jay Borschel": {falls:24,bouts:108,source:"https://hawkeyesports.com/sports/wrestling/roster/player/jay-borschel"},
  "Sammy Brooks": {falls:27,bouts:126,source:"https://hawkeyesports.com/sports/wrestling/roster/player/sammy-brooks"},
  "Vincenzo Joseph": {falls:25,bouts:98,source:"https://lehighsports.com/staff-directory/vincenzo-joseph/1277"},
  "Alan Waters": {falls:27,bouts:150,source:"https://mutigers.com/sports/wrestling/roster/player/alan-waters"},
  "Mark Ellis": {falls:30,bouts:129,source:"https://mutigers.com/honors/hall-of-fame/mark-ellis/211/kiosk"},
  "Keegan O'Toole": {falls:31,bouts:113,source:"https://mutigers.com/sports/wrestling/roster/season/2023-24/player/keegan-otoole"},
  "Drake Houdashelt": {falls:18,bouts:157,source:"https://mutigers.com/sports/wrestling/roster/player/drake-houdashelt"},
  "Brent Metcalf": {falls:47,bouts:111,source:"https://hawkeyesports.com/sports/wrestling/roster/season/2009-10/player/brent-metcalf"},
  "Tommy Rowlands": {falls:30,bouts:179,source:"https://nwhof.org/national-wrestling-hall-of-fame/champions-database?tab=ncaa&wrestler=5904"},
  "Adam Tirapelle": {falls:33,bouts:148,source:"https://fightingillini.com/honors/hall-of-fame/adam-tirapelle/72/kiosk"},
  "John Hughes": {falls:14,bouts:149,source:"https://nwhof.org/hall_of_fame/bio/6323"},
  "Aaron Brooks": {falls:16,bouts:92,source:"https://gopsusports.com/news/2024/06/17/brooks-nemeth-named-penn-state-athletes-of-the-year"},
  "Dan Hodge": {falls:36,bouts:46,source:"https://nwhof.org/national-wrestling-hall-of-fame/bio/6"},
  "Jeff Prescott": {falls:21,bouts:105,source:"https://nwhof.org/hall_of_fame/bio/6532"},
  "Quentin Wright": {falls:37,bouts:139,source:"https://gopsusports.com/news/2013/03/24/nittany-lions-win-third-straight-ncaa-wrestling-crown"},
  "Nick Lee": {falls:18,bouts:131,source:"https://gopsusports.com/staff/nick-lee"},
  "Cary Kolat": {falls:53,bouts:118,source:"https://navysports.com/news/2020/3/20/cary-kolat-named-navy-head-wrestling-coach.aspx?path=me"},
  "Kerry McCoy": {falls:34,bouts:168,source:"https://nwhof.org/national-wrestling-hall-of-fame/bio/1272"},
  "Eric Juergens": {falls:23,bouts:133,source:"https://hawkeyesports.com/news/2019/08/05/wrestling-hall-of-fame-spotlight-eric-juergens"},
  "Steve Mocco": {falls:56,bouts:143,source:"https://nwhof.org/national-wrestling-hall-of-fame/bio/12557"},
  "Alex Dieringer": {falls:45,bouts:137,source:"https://d1yllc564ye8is.cloudfront.net/sports/2015/3/17/GEN_2014010114"},
  "Jordan Oliver": {falls:54,bouts:133,source:"https://okstate.com/news/2015/11/9/WREST_1109152432"},
  "Pat Smith": {falls:30,bouts:128,source:"https://nwhof.org/hall_of_fame/bio/1498"},
  'Jake Varner': {falls:42,bouts:131,source:'https://cyclones.com/sports/wrestling/roster/jake-varner/2862'},
  'Trent Paulson': {falls:15,bouts:137,source:'https://nwhof.org/hall_of_fame/bio_by_name/trent-paulson'},
  'Jason Nolf': { falls: 60, bouts: 120, source: 'https://gopsusports.com/news/2019/04/1/nolf-and-ogle-named-mccoy-award-winners-crow-garners-walker-award-mchugh-earns-oswald' },
  'Bo Nickal': { falls: 59, bouts: 123, gorriaranYears: [2017], source: 'https://gopsusports.com/news/2019/04/1/bo-nickal-wins-the-hodge' },
  'Zain Retherford': { falls: 53, bouts: 129, source: 'https://gopsusports.com/news/2018/03/26/wr-zain-wins-the-hodge-again' },
  'Ed Ruth': { falls: 46, bouts: 139, source: 'https://gopsusports.com/news/2014/09/5/former-lion-great-ed-ruth-ready-for-world-freestyle-championships' },
  'David Taylor': { falls: 53, bouts: 137, gorriaranYears: [2013], gorriaranSource: 'https://s3.us-east-2.amazonaws.com/sidearm.nextgen.sites/nwca.sidearmsports.com/documents/2023/11/14/NCAA_Championship_2013.pdf#page=1', source: 'https://gopsusports.com/news/2014/03/23/penn-state-wrestlers-win-fourth-straight-national-championship' },
  'Mark Perry': { gorriaranYears: [2006], source: 'https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=72' },
  'Jayson Ness': { falls: 73, bouts: 163, source: 'https://gophersports.com/news/2010/3/26/jayson_ness_wins_hodge_trophy' },
  'Logan Stieber': { falls: 50, bouts: 122, source: pastHodge },
};

/** Rates avoid rewarding an extra eligibility year merely for more bouts. */
export function pinningMultiplier(name: string): number {
  const history = PIN_HISTORY[name];
  if (!history) return 1;
  const rate = history.falls !== undefined && history.bouts ? history.falls / history.bouts : 0;
  return Math.min(1.4, 1 + rate * 0.5 + (history.gorriaranYears?.length ? 0.1 : 0));
}
