import { HODGE_AWARDS } from './careerAwards';
/** NCAA tournament results only; no invented points for cancelled events or missing data. */
export interface NcaaSeason {
  year: number;
  place: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 'qualifier';
  outstandingWrestler?: boolean;
  source: string;
}
export interface CareerScore {
  counted: Array<NcaaSeason & { points: number }>;
  excluded: Array<NcaaSeason & { points: number }>;
  placementPoints: number;
  bonusPoints: number;
  total: number;
  eligibilitySeasons: 3 | 4;
  averagePlacementPoints: number;
  averagePoints: number;
  tier: string;
  provisionalRating: number;
}
export function seasonPoints(season: NcaaSeason): number {
  // 3rd = 7: the owner's 10/9/…/2 scale leaves 8 unused.
  const placement = season.place === 0 ? 0 : season.place === 'qualifier' ? 1 : season.place <= 2 ? 11 - season.place : 10 - season.place;
  return placement + (season.outstandingWrestler ? 1 : 0);
}
export function scoreCareer(seasons: readonly NcaaSeason[], eligibilitySeasons: 3 | 4 = 4): CareerScore {
  if (new Set(seasons.map(s => s.year)).size !== seasons.length) throw new Error('Duplicate NCAA season');
  const sorted = seasons.map(s => {
    if (!Number.isInteger(s.year) || (s.place !== 'qualifier' && (!Number.isInteger(s.place) || s.place < 0 || s.place > 8))) throw new Error('Invalid NCAA result');
    return {...s, points: seasonPoints(s)};
  }).sort((a, b) => b.points - a.points || b.year - a.year);
  const counted = sorted.slice(0, eligibilitySeasons);
  const bonusPoints = counted.filter(s => s.outstandingWrestler).length;
  const total = counted.reduce((sum, s) => sum + s.points, 0);
  const averagePlacementPoints = (total - bonusPoints) / eligibilitySeasons;
  const tier = averagePlacementPoints >= 10 ? 'Champion' : averagePlacementPoints >= 9 ? 'Finalist' : averagePlacementPoints >= 7 ? 'Top three' : averagePlacementPoints >= 2 ? 'All-American' : 'Qualifier';
  return {counted, excluded: sorted.slice(eligibilitySeasons), placementPoints: total - bonusPoints, bonusPoints, total,
    eligibilitySeasons, averagePlacementPoints, averagePoints: total / eligibilitySeasons, tier,
    provisionalRating: Math.min(championshipCeiling(counted), Math.round(placementRating(averagePlacementPoints) + bonusPoints))};
}
const gableSource = 'https://nwhof.org/national-wrestling-hall-of-fame/champions-database?tab=ncaa&wrestler=38';
export const CAREER_RECORDS: Record<string, NcaaSeason[]> = {
  "Sammy Brooks": [{year:2014,place:0,source:"https://hawkeyesports.com/sports/wrestling/roster/player/sammy-brooks"},{year:2015,place:"qualifier",source:"https://hawkeyesports.com/sports/wrestling/roster/player/sammy-brooks"},{year:2016,place:8,source:"https://hawkeyesports.com/sports/wrestling/roster/player/sammy-brooks"},{year:2017,place:4,source:"https://hawkeyesports.com/sports/wrestling/roster/player/sammy-brooks"}],
  "Vincenzo Joseph": [{year:2017,place:1,source:"https://lehighsports.com/staff-directory/vincenzo-joseph/1277"},{year:2018,place:1,source:"https://lehighsports.com/staff-directory/vincenzo-joseph/1277"},{year:2019,place:2,source:"https://lehighsports.com/staff-directory/vincenzo-joseph/1277"}],
  "Tyler McCormick": [{year:2005,place:0,source:"https://mutigers.com/documents/download/2020/2/17/History_Records.pdf#page=41"},{year:2006,place:7,source:"https://mutigers.com/documents/download/2020/2/17/History_Records.pdf#page=41"},{year:2007,place:6,source:"https://mutigers.com/documents/download/2020/2/17/History_Records.pdf#page=42"},{year:2008,place:"qualifier",source:"https://mutigers.com/documents/download/2020/2/17/History_Records.pdf#page=42"}],
  "Jaydin Eierman": [{"year": 2017, "place": 5, "source": "https://hawkeyesports.com/sports/wrestling/roster/season/2021-22/player/jaydin-eierman"}, {"year": 2018, "place": 4, "source": "https://hawkeyesports.com/sports/wrestling/roster/season/2021-22/player/jaydin-eierman"}, {"year": 2019, "place": 3, "source": "https://hawkeyesports.com/sports/wrestling/roster/season/2021-22/player/jaydin-eierman"}, {"year": 2021, "place": 2, "source": "https://hawkeyesports.com/sports/wrestling/roster/season/2021-22/player/jaydin-eierman"}, {"year": 2022, "place": "qualifier", "source": "https://s3.us-east-2.amazonaws.com/sidearm.nextgen.sites/nwca.sidearmsports.com/documents/2023/11/14/NCAA_Championship_2022.pdf"}],
  "Michael Chandler": [{"year": 2006, "place": "qualifier", "source": "https://mutigers.com/sports/wrestling/roster/season/2008-09/player/michael-chandler"}, {"year": 2007, "place": "qualifier", "source": "https://mutigers.com/sports/wrestling/roster/season/2008-09/player/michael-chandler"}, {"year": 2008, "place": "qualifier", "source": "https://mutigers.com/sports/wrestling/roster/season/2008-09/player/michael-chandler"}, {"year": 2009, "place": 5, "source": "https://mutigers.com/news/2013/01/17/mizzou-alum-and-mma-lightweight-champion-michael-chandler-to-defend-title-tonight"}],
  "Alan Waters": [{"year": 2011, "place": "qualifier", "source": "https://mutigers.com/sports/wrestling/roster/player/alan-waters"}, {"year": 2012, "place": "qualifier", "source": "https://mutigers.com/sports/wrestling/roster/player/alan-waters"}, {"year": 2013, "place": 4, "source": "https://mutigers.com/sports/wrestling/roster/player/alan-waters"}, {"year": 2015, "place": 3, "source": "https://mutigers.com/news/2015/03/21/waters-takes-third-cox-takes-fifth-at-ncaa-championships-session-5"}],
  "Mark Ellis": [{"year": 2007, "place": "qualifier", "source": "https://mutigers.com/sports/wrestling/roster/player/mark-ellis"}, {"year": 2008, "place": "qualifier", "source": "https://mutigers.com/sports/wrestling/roster/player/mark-ellis"}, {"year": 2009, "place": 1, "source": "https://mutigers.com/honors/hall-of-fame/mark-ellis/211/kiosk"}, {"year": 2010, "place": 6, "source": "https://mutigers.com/honors/hall-of-fame/mark-ellis/211/kiosk"}],

  "J'den Cox": [{"year": 2014, "place": 1, "source": "https://mutigers.com/sports/wrestling/roster/player/jden-cox"}, {"year": 2015, "place": 5, "source": "https://mutigers.com/news/2016/3/20/wrestling-cox-becomes-second-ever-two-time-national-champion-in-program-history"}, {"year": 2016, "place": 1, "source": "https://mutigers.com/sports/wrestling/roster/player/jden-cox"}, {"year": 2017, "place": 1, "source": "https://mutigers.com/sports/wrestling/roster/player/jden-cox"}],
  "Keegan O'Toole": [{"year": 2021, "place": 3, "source": "https://mutigers.com/sports/wrestling/roster/season/2023-24/player/keegan-otoole"}, {"year": 2022, "place": 1, "source": "https://mutigers.com/sports/wrestling/roster/season/2023-24/player/keegan-otoole"}, {"year": 2023, "place": 1, "source": "https://mutigers.com/sports/wrestling/roster/season/2023-24/player/keegan-otoole"}, {"year": 2024, "place": 3, "source": "https://mutigers.com/sports/wrestling/roster/season/2023-24/player/keegan-otoole"}, {"year": 2025, "place": 2, "source": "https://mutigers.com/sports/wrestling/roster/season/2023-24/player/keegan-otoole"}],

  "Drake Houdashelt": [{"year": 2012, "place": "qualifier", "source": "https://mutigers.com/sports/wrestling/roster/player/drake-houdashelt"}, {"year": 2013, "place": 6, "source": "https://mutigers.com/sports/wrestling/roster/player/drake-houdashelt"}, {"year": 2014, "place": 5, "source": "https://mutigers.com/sports/wrestling/roster/player/drake-houdashelt"}, {"year": 2015, "place": 1, "source": "https://mutigers.com/sports/wrestling/roster/player/drake-houdashelt"}],
  "Brent Metcalf": [{"year": 2008, "place": 1, "source": "https://hawkeyesports.com/sports/wrestling/roster/season/2009-10/player/brent-metcalf", "outstandingWrestler": true}, {"year": 2009, "place": 2, "source": "https://hawkeyesports.com/sports/wrestling/roster/season/2009-10/player/brent-metcalf"}, {"year": 2010, "place": 1, "source": "https://hawkeyesports.com/sports/wrestling/roster/season/2009-10/player/brent-metcalf"}],
  "Max Askren": [{"year": 2007, "place": "qualifier", "source": "https://mutigers.com/sports/wrestling/roster/season/2008-09/player/maxwell-askren"}, {"year": 2008, "place": 7, "source": "https://mutigers.com/sports/wrestling/roster/season/2008-09/player/maxwell-askren"}, {"year": 2009, "place": 5, "source": "https://mutigers.com/sports/wrestling/roster/season/2008-09/player/maxwell-askren"}, {"year": 2010, "place": 1, "source": "https://mutigers.com/sports/wrestling/roster/season/2008-09/player/maxwell-askren"}],
  "Ben Askren": [{"year": 2004, "place": 2, "source": "https://mutigers.com/news/2012/01/09/class-of-six-chosen-for-mu-athletics-hall-of-fame"}, {"year": 2005, "place": 2, "source": "https://mutigers.com/news/2012/01/09/class-of-six-chosen-for-mu-athletics-hall-of-fame"}, {"year": 2006, "place": 1, "source": "https://more.mutigers.com/mizzoumade/askren.html", "outstandingWrestler": true}, {"year": 2007, "place": 1, "source": "https://mutigers.com/news/2012/01/09/class-of-six-chosen-for-mu-athletics-hall-of-fame"}],
  "Nathan Tomasello": [{"year": 2015, "place": 1, "source": "https://ohiostatebuckeyes.com/sports/wrestling/roster/nathan-tomasello/2226"}, {"year": 2016, "place": 3, "source": "https://ohiostatebuckeyes.com/sports/wrestling/roster/nathan-tomasello/2226"}, {"year": 2017, "place": 3, "source": "https://ohiostatebuckeyes.com/sports/wrestling/roster/nathan-tomasello/2226"}, {"year": 2018, "place": 3, "source": "https://ohiostatebuckeyes.com/sports/wrestling/roster/nathan-tomasello/2226"}],
  "Nick Heflin": [{"year": 2011, "place": "qualifier", "source": "https://ohiostatebuckeyes.com/news/2011/3/18/colt-sponseller-advances-to-ncaa-championships-quarterfinals"}, {"year": 2012, "place": 5, "source": "https://ohiostatebuckeyes.com/news/2012/11/1/ohio-state-names-2012-13-team-captains"}, {"year": 2013, "place": 5, "source": "https://ohiostatebuckeyes.com/documents/download/2023/5/25/1213year-in-review.pdf"}, {"year": 2014, "place": 2, "source": "https://ohiostatebuckeyes.com/news/2014/3/25/ohio-state-athletics-good-stuff-28"}],
  "Tommy Rowlands": [{"year": 2001, "place": 2, "source": "https://ohiostatebuckeyes.com/documents/download/2023/6/1/2012_13TeamGuide.pdf#page=33"}, {"year": 2002, "place": 1, "source": "https://ohiostatebuckeyes.com/honors/hall-of-fame-inductees/tommy-rowlands/362"}, {"year": 2003, "place": 6, "source": "https://ohiostatebuckeyes.com/documents/download/2023/6/1/2012_13TeamGuide.pdf#page=33"}, {"year": 2004, "place": 1, "source": "https://ohiostatebuckeyes.com/honors/hall-of-fame-inductees/tommy-rowlands/362"}],
  "Jesse Delgado": [{"year": 2012, "place": 7, "source": "https://fightingillini.com/sports/wrestling/roster/jesse-delgado/1529"}, {"year": 2013, "place": 1, "source": "https://fightingillini.com/sports/wrestling/roster/jesse-delgado/1529"}, {"year": 2014, "place": 1, "source": "https://fightingillini.com/sports/wrestling/roster/jesse-delgado/1529"}, {"year": 2015, "place": "qualifier", "source": "https://fightingillini.com/sports/wrestling/roster/jesse-delgado/1529"}],
  "Adam Tirapelle": [{"year": 1998, "place": "qualifier", "source": "https://fightingillini.com/honors/hall-of-fame/adam-tirapelle/72/kiosk"}, {"year": 1999, "place": 3, "source": "https://fightingillini.com/honors/hall-of-fame/adam-tirapelle/72/kiosk"}, {"year": 2000, "place": 2, "source": "https://fightingillini.com/honors/hall-of-fame/adam-tirapelle/72/kiosk"}, {"year": 2001, "place": 1, "source": "https://fightingillini.com/honors/hall-of-fame/adam-tirapelle/72/kiosk"}],
  "Yianni Diakomihalis": [{"year": 2018, "place": 1, "source": "https://cornellbigred.com/aa.aspx?hid=686"}, {"year": 2019, "place": 1, "source": "https://cornellbigred.com/aa.aspx?hid=686"}, {"year": 2022, "place": 1, "source": "https://cornellbigred.com/aa.aspx?hid=686"}, {"year": 2023, "place": 1, "source": "https://cornellbigred.com/aa.aspx?hid=686"}],
  "Vito Arujau": [{"year": 2019, "place": 4, "source": "https://cornellbigred.com/aa.aspx?hid=701"}, {"year": 2022, "place": 3, "source": "https://cornellbigred.com/aa.aspx?hid=701"}, {"year": 2023, "place": 1, "source": "https://cornellbigred.com/news/2023/3/18/wrestling-day-3-recap-ncaa.aspx", "outstandingWrestler": true}, {"year": 2024, "place": 1, "source": "https://cornellbigred.com/aa.aspx?hid=701"}],
  "John Hughes": [{"year": 1992, "place": "qualifier", "source": "https://nwhof.org/brackets/62#page=11"}, {"year": 1994, "place": 7, "source": "https://nwhof.org/hall_of_fame/bio/6323"}, {"year": 1995, "place": 1, "source": "https://nwhof.org/hall_of_fame/bio/6323"}, {"year": 1996, "place": 2, "source": "https://nwhof.org/hall_of_fame/bio/6323"}],
  "Aaron Brooks": [{"year": 2021, "place": 1, "source": "https://gopsusports.com/news/2021/03/21/penn-state-perfect-in-the-ncaa-finals"}, {"year": 2022, "place": 1, "source": "https://gopsusports.com/news/2022/03/20/penn-state-perfect-nittany-lions-cap-off-team-title-with-5-0-run-in-ncaa-finals"}, {"year": 2023, "place": 1, "source": "https://gopsusports.com/news/2023/03/19/starocci-and-brooks-win-individual-titles-for-national-champion-wrestling-team"}, {"year": 2024, "place": 1, "source": "https://gopsusports.com/news/2024/03/23/four-nittany-lions-win-ncaa-titles-for-2024-national-champion-penn-state-wrestling-team", "outstandingWrestler": true}],
  "Carter Starocci": [{"year": 2021, "place": 1, "source": "https://gopsusports.com/news/2021/03/21/penn-state-perfect-in-the-ncaa-finals"}, {"year": 2022, "place": 1, "source": "https://gopsusports.com/news/2022/03/20/penn-state-perfect-nittany-lions-cap-off-team-title-with-5-0-run-in-ncaa-finals"}, {"year": 2023, "place": 1, "source": "https://gopsusports.com/news/2023/03/19/starocci-and-brooks-win-individual-titles-for-national-champion-wrestling-team"}, {"year": 2024, "place": 1, "source": "https://gopsusports.com/news/2024/03/23/four-nittany-lions-win-ncaa-titles-for-2024-national-champion-penn-state-wrestling-team"}, {"year": 2025, "place": 1, "source": "https://gopsusports.com/news/2025/3/22/national-champion-penn-state-crowns-two-individual-titlists-to-close-out-2025-ncaa-wrestling-championships-in-philadelphia", "outstandingWrestler": true}],
  "Dan Hodge": [{"year": 1955, "place": 1, "source": "https://nwhof.org/brackets/26#page=1"}, {"year": 1956, "place": 1, "source": "https://nwhof.org/brackets/27#page=1", "outstandingWrestler": true}, {"year": 1957, "place": 1, "source": "https://nwhof.org/brackets/28#page=1", "outstandingWrestler": true}],
  "Jeff Prescott": [{"year": 1989, "place": 0, "source": "https://nwhof.org/brackets/59#page=2"}, {"year": 1990, "place": 5, "source": "https://nwhof.org/hall_of_fame/bio/6532"}, {"year": 1991, "place": 1, "outstandingWrestler": true, "source": "https://s3.us-east-2.amazonaws.com/sidearm.nextgen.sites/nwca.sidearmsports.com/documents/2023/11/14/NCAA_Championship_1991.pdf"}, {"year": 1992, "place": 1, "source": "https://nwhof.org/hall_of_fame/bio/6532"}],
  "Quentin Wright": [{"year": 2009, "place": 6, "source": "https://gopsusports.com/news/2013/03/24/nittany-lions-win-third-straight-ncaa-wrestling-crown"}, {"year": 2011, "place": 1, "source": "https://gopsusports.com/news/2013/03/24/nittany-lions-win-third-straight-ncaa-wrestling-crown"}, {"year": 2012, "place": 2, "source": "https://gopsusports.com/news/2013/03/24/nittany-lions-win-third-straight-ncaa-wrestling-crown"}, {"year": 2013, "place": 1, "source": "https://gopsusports.com/news/2013/03/24/nittany-lions-win-third-straight-ncaa-wrestling-crown"}],
  "Roman Bravo-Young": [{"year": 2019, "place": 8, "source": "https://gopsusports.com/news/2019/03/23/nittany-lion-wrestlers-clinch-2019-ncaa-national-championship"}, {"year": 2021, "place": 1, "source": "https://gopsusports.com/news/2021/03/21/penn-state-perfect-in-the-ncaa-finals"}, {"year": 2022, "place": 1, "source": "https://gopsusports.com/news/2022/03/20/penn-state-perfect-nittany-lions-cap-off-team-title-with-5-0-run-in-ncaa-finals"}, {"year": 2023, "place": 2, "source": "https://gopsusports.com/news/2023/03/19/starocci-and-brooks-win-individual-titles-for-national-champion-wrestling-team"}],
  "Nick Lee": [{"year": 2018, "place": 5, "source": "https://gopsusports.com/staff/nick-lee"}, {"year": 2019, "place": 5, "source": "https://gopsusports.com/staff/nick-lee"}, {"year": 2021, "place": 1, "source": "https://gopsusports.com/staff/nick-lee"}, {"year": 2022, "place": 1, "source": "https://gopsusports.com/staff/nick-lee"}],
  "Sanshiro Abe": [{"year": 1993, "place": 4, "source": "https://nwhof.org/brackets/63#page=1"}, {"year": 1994, "place": 3, "source": "https://nwhof.org/brackets/64#page=1"}, {"year": 1995, "place": 2, "source": "https://nwhof.org/brackets/65#page=1"}, {"year": 1996, "place": 1, "source": "https://nwhof.org/brackets/66#page=1"}],
  "Cary Kolat": [{"year": 1993, "place": 2, "source": "https://nwhof.org/brackets/63#page=1"}, {"year": 1994, "place": 3, "source": "https://nwhof.org/brackets/64#page=1"}, {"year": 1996, "place": 1, "source": "https://nwhof.org/brackets/66#page=1"}, {"year": 1997, "place": 1, "source": "https://nwhof.org/brackets/67#page=1"}],
  "Kerry McCoy": [{"year": 1993, "place": "qualifier", "source": "https://nwhof.org/brackets/63#page=26"}, {"year": 1994, "place": 1, "source": "https://nwhof.org/national-wrestling-hall-of-fame/bio/1272"}, {"year": 1995, "place": 3, "source": "https://nwhof.org/national-wrestling-hall-of-fame/bio/1272"}, {"year": 1997, "place": 1, "source": "https://nwhof.org/national-wrestling-hall-of-fame/bio/1272"}],
  "Lou Banach": [{"year": 1980, "place": 0, "source": "https://nwhof.org/brackets/50#page=29"}, {"year": 1981, "place": 1, "source": "https://nwhof.org/hall_of_fame/bio/93"}, {"year": 1982, "place": 3, "source": "https://nwhof.org/hall_of_fame/bio/93"}, {"year": 1983, "place": 1, "source": "https://nwhof.org/hall_of_fame/bio/93"}],
  "Eric Juergens": [{"year": 1998, "place": 3, "source": "https://nwhof.org/hall_of_fame/bio_by_name/eric-juergens"}, {"year": 1999, "place": 3, "source": "https://nwhof.org/hall_of_fame/bio_by_name/eric-juergens"}, {"year": 2000, "place": 1, "source": "https://nwhof.org/hall_of_fame/bio_by_name/eric-juergens"}, {"year": 2001, "place": 1, "source": "https://nwhof.org/hall_of_fame/bio_by_name/eric-juergens"}],
  "Steve Mocco": [{"year": 2002, "place": 2, "source": "https://nwhof.org/national-wrestling-hall-of-fame/bio/12557"}, {"year": 2003, "place": 1, "source": "https://nwhof.org/national-wrestling-hall-of-fame/bio/12557"}, {"year": 2005, "place": 1, "source": "https://nwhof.org/national-wrestling-hall-of-fame/bio/12557"}, {"year": 2006, "place": 2, "source": "https://nwhof.org/national-wrestling-hall-of-fame/bio/12557"}],
  "Kenny Monday": [{"year": 1981, "place": "qualifier", "source": "https://nwhof.org/brackets/51#page=11"}, {"year": 1982, "place": 2, "source": "https://nwhof.org/hall_of_fame/bio/377"}, {"year": 1983, "place": 2, "source": "https://nwhof.org/hall_of_fame/bio/377"}, {"year": 1984, "place": 1, "source": "https://nwhof.org/hall_of_fame/bio/377"}],
  "Dean Heil": [{"year": 2015, "place": 4, "source": "https://gocamels.com/sports/wrestling/roster/coaches/dean-heil/465"}, {"year": 2016, "place": 1, "source": "https://gocamels.com/sports/wrestling/roster/coaches/dean-heil/465"}, {"year": 2017, "place": 1, "source": "https://gocamels.com/sports/wrestling/roster/coaches/dean-heil/465"}, {"year": 2018, "place": "qualifier", "source": "https://gocamels.com/sports/wrestling/roster/coaches/dean-heil/465"}],
  "Mark Branch": [{"year": 1994, "place": 1, "source": "https://gowyo.com/sports/wrestling/roster/coaches/mark-branch/1410"}, {"year": 1995, "place": 2, "source": "https://gowyo.com/sports/wrestling/roster/coaches/mark-branch/1410"}, {"year": 1996, "place": 2, "source": "https://gowyo.com/sports/wrestling/roster/coaches/mark-branch/1410"}, {"year": 1997, "place": 1, "source": "https://gowyo.com/sports/wrestling/roster/coaches/mark-branch/1410"}],
  "Mike Sheets": [{"year": 1981, "place": 7, "source": "https://nwhof.org/national-wrestling-hall-of-fame/bio/6987"}, {"year": 1982, "place": 2, "source": "https://nwhof.org/national-wrestling-hall-of-fame/bio/6987"}, {"year": 1983, "place": 1, "source": "https://okstate.com/news/2015/10/22/WREST_1022154158", "outstandingWrestler": true}, {"year": 1984, "place": 1, "source": "https://nwhof.org/national-wrestling-hall-of-fame/bio/6987"}],

  "Johnny Thompson": [{"year": 2001, "place": 2, "source": "https://okstate.com/news/2003/9/23/Johnny_Thompson"}, {"year": 2002, "place": 1, "source": "https://okstate.com/news/2003/9/23/Johnny_Thompson"}, {"year": 2003, "place": 1, "source": "https://okstate.com/news/2003/9/23/Johnny_Thompson"}, {"year": 2004, "place": 3, "source": "https://okstate.com/news/2015/11/4/WREST_1104153308"}],
  "Eric Guerrero": [{"year": 1996, "place": 5, "source": "https://nwhof.org/hall_of_fame/bio/3348"}, {"year": 1997, "place": 1, "source": "https://okstate.com/news/2009/2/27/Eric_Guerrero"}, {"year": 1998, "place": 1, "source": "https://okstate.com/news/2009/2/27/Eric_Guerrero"}, {"year": 1999, "place": 1, "source": "https://okstate.com/news/2009/2/27/Eric_Guerrero"}],
  "Zack Esposito": [{"year": 2003, "place": "qualifier", "source": "https://okstate.com/news/2005/10/6/Zack_Esposito"}, {"year": 2004, "place": 2, "source": "https://okstate.com/news/2005/10/6/Zack_Esposito"}, {"year": 2005, "place": 1, "source": "https://okstate.com/news/2005/10/6/Zack_Esposito"}, {"year": 2006, "place": 3, "source": "https://okstate.com/news/2006/3/27/Cowboys_Take_Home_Fourth_Consecutive_Wrestling_Title_Crown_Two_Champions"}],

  "Chris Pendleton": [{"year": 2001, "place": "qualifier", "source": "https://okstate.com/news/2001/3/15/Cowboys_wrestlers_in_third_following_the_morning_session"}, {"year": 2003, "place": 3, "source": "https://okstate.com/news/2004/10/12/Chris_Pendleton"}, {"year": 2004, "place": 1, "source": "https://okstate.com/news/2004/10/12/Chris_Pendleton"}, {"year": 2005, "place": 1, "source": "https://okstate.com/news/2015/11/4/WREST_1104153308"}],
  "Jake Rosholt": [{"year": 2003, "place": 1, "source": "https://okstate.com/news/2005/10/6/Jake_Rosholt"}, {"year": 2004, "place": 3, "source": "https://okstate.com/news/2005/10/6/Jake_Rosholt"}, {"year": 2005, "place": 1, "source": "https://okstate.com/news/2005/10/6/Jake_Rosholt"}, {"year": 2006, "place": 1, "source": "https://okstate.com/news/2015/11/4/WREST_1104153308"}],

  "Johny Hendricks": [{"year": 2004, "place": 5, "source": "https://okstate.com/news/2006/10/30/Johny_Hendricks"}, {"year": 2005, "place": 1, "source": "https://okstate.com/news/2006/10/30/Johny_Hendricks"}, {"year": 2006, "place": 1, "source": "https://okstate.com/news/2006/10/30/Johny_Hendricks"}, {"year": 2007, "place": 2, "source": "https://okstate.com/news/2015/11/4/WREST_1104153308"}],
  "Chris Perry": [{"year": 2011, "place": "qualifier", "source": "https://okstate.com/sports/wrestling/roster/chris-perry/1728"}, {"year": 2012, "place": 3, "source": "https://okstate.com/sports/wrestling/roster/chris-perry/1728"}, {"year": 2013, "place": 1, "source": "https://okstate.com/sports/wrestling/roster/chris-perry/1728"}, {"year": 2014, "place": 1, "source": "https://okstate.com/sports/wrestling/roster/chris-perry/1728"}],

  "Alex Dieringer": [{"year": 2013, "place": 3, "source": "https://okstate.com/sports/wrestling/roster/alex-dieringer/3042"}, {"year": 2014, "place": 1, "source": "https://okstate.com/sports/wrestling/roster/alex-dieringer/3042"}, {"year": 2015, "place": 1, "source": "https://okstate.com/sports/wrestling/roster/alex-dieringer/3042"}, {"year": 2016, "place": 1, "source": "https://okstate.com/sports/wrestling/roster/alex-dieringer/3042"}],
  "Jordan Oliver": [{"year": 2010, "place": 4, "source": "https://okstate.com/sports/wrestling/roster/jordan-oliver/1763"}, {"year": 2011, "place": 1, "source": "https://okstate.com/sports/wrestling/roster/jordan-oliver/1763"}, {"year": 2012, "place": 2, "source": "https://okstate.com/sports/wrestling/roster/jordan-oliver/1763"}, {"year": 2013, "place": 1, "source": "https://okstate.com/news/2013/4/2/cowboy_wrestling_season_in_review"}],
  "John Smith": [{"year": 1984, "place": "qualifier", "source": "https://nwhof.org/brackets/54#page=5"}, {"year": 1985, "place": 2, "source": "https://s3.us-east-2.amazonaws.com/sidearm.nextgen.sites/nwca.sidearmsports.com/documents/2023/11/14/NCAA_Championship_1985.pdf#page=1"}, {"year": 1987, "place": 1, "outstandingWrestler": true, "source": "https://okstate.com/news/2015/10/22/WREST_1022154158"}, {"year": 1988, "place": 1, "source": "https://okstate.com/news/2003/11/5/Hall_of_Honor"}],
  "Pat Smith": [{"year": 1990, "place": 1, "source": "https://nwhof.org/hall_of_fame/bio/1498"}, {"year": 1991, "place": 1, "source": "https://nwhof.org/hall_of_fame/bio/1498"}, {"year": 1992, "place": 1, "source": "https://nwhof.org/hall_of_fame/bio/1498"}, {"year": 1994, "place": 1, "source": "https://nwhof.org/hall_of_fame/bio/1498", "outstandingWrestler": true}],
  "Kyle Snyder": [{"year": 2015, "place": 2, "source": "https://ohiostatebuckeyes.com/sports/wrestling/roster/kyle-snyder/2210"}, {"year": 2016, "place": 1, "source": "https://ohiostatebuckeyes.com/sports/wrestling/roster/kyle-snyder/2210", "outstandingWrestler": true}, {"year": 2017, "place": 1, "source": "https://ohiostatebuckeyes.com/sports/wrestling/roster/kyle-snyder/2210"}, {"year": 2018, "place": 1, "source": "https://ohiostatebuckeyes.com/sports/wrestling/roster/kyle-snyder/2210"}],
  "Jordan Burroughs": [{"year": 2007, "place": "qualifier", "source": "https://huskers.com/sports/wrestling/roster/season/2010-11/player/jordan-burroughs"}, {"year": 2008, "place": 3, "source": "https://huskers.com/sports/wrestling/roster/season/2010-11/player/jordan-burroughs"}, {"year": 2009, "place": 1, "source": "https://huskers.com/sports/wrestling/roster/season/2010-11/player/jordan-burroughs"}, {"year": 2011, "place": 1, "source": "https://huskers.com/sports/wrestling/roster/season/2010-11/player/jordan-burroughs"}],
  "Nate Carr": [{"year": 1980, "place": "qualifier", "source": "https://cyclones.com/documents/download/2023/6/12/Record_Book.pdf#page=13"}, {"year": 1981, "place": 1, "source": "https://cyclones.com/documents/download/2023/6/12/Record_Book.pdf#page=7"}, {"year": 1982, "place": 1, "source": "https://cyclones.com/documents/download/2023/6/12/Record_Book.pdf#page=7"}, {"year": 1983, "place": 1, "source": "https://cyclones.com/documents/download/2023/6/12/Record_Book.pdf#page=7"}],
  "Tim Krieger": [{"year": 1986, "place": 5, "source": "https://cyclones.com/sports/2015/3/2/GEN_20140101173"}, {"year": 1987, "place": 1, "source": "https://cyclones.com/sports/2015/3/2/GEN_20140101173"}, {"year": 1988, "place": 2, "source": "https://cyclones.com/sports/2015/3/2/GEN_20140101173"}, {"year": 1989, "place": 1, "source": "https://cyclones.com/sports/2015/3/2/GEN_20140101173", "outstandingWrestler": true}],
  "Jake Varner": [{"year": 2007, "place": 2, "source": "https://cyclones.com/honors/hall-of-fame/jake-varner/198?path=general"}, {"year": 2008, "place": 2, "source": "https://cyclones.com/honors/hall-of-fame/jake-varner/198?path=general"}, {"year": 2009, "place": 1, "source": "https://cyclones.com/honors/hall-of-fame/jake-varner/198?path=general"}, {"year": 2010, "place": 1, "source": "https://cyclones.com/honors/hall-of-fame/jake-varner/198?path=general"}],
  "Jon Reader": [{"year": 2008, "place": 7, "source": "https://cyclones.com/news/2011/3/25/205123068"}, {"year": 2009, "place": 4, "source": "https://cyclones.com/news/2011/3/25/205123068"}, {"year": 2010, "place": "qualifier", "source": "https://cyclones.com/news/2011/3/25/205123068"}, {"year": 2011, "place": 1, "source": "https://cyclones.com/news/2011/3/25/205123068"}],
  "Zach Roberson": [{"year": 2001, "place": "qualifier", "source": "https://cyclones.com/staff-directory/zach-roberson/332"}, {"year": 2002, "place": 7, "source": "https://cyclones.com/staff-directory/zach-roberson/332"}, {"year": 2003, "place": 4, "source": "https://cyclones.com/staff-directory/zach-roberson/332"}, {"year": 2004, "place": 1, "source": "https://cyclones.com/staff-directory/zach-roberson/332"}],
  "David Zabriskie": [{"year": 2007, "place": "qualifier", "source": "https://cyclones.com/sports/wrestling/roster/david-zabriskie/2876"}, {"year": 2008, "place": 6, "source": "https://cyclones.com/sports/wrestling/roster/david-zabriskie/2876"}, {"year": 2009, "place": 5, "source": "https://cyclones.com/sports/wrestling/roster/david-zabriskie/2876"}, {"year": 2010, "place": 1, "source": "https://cyclones.com/sports/wrestling/roster/david-zabriskie/2876"}],
  "Kyven Gadson": [{"year": 2012, "place": 0, "source": "https://cyclones.com/sports/wrestling/roster/kyven-gadson/1279"}, {"year": 2013, "place": 6, "source": "https://cyclones.com/sports/wrestling/roster/kyven-gadson/1279"}, {"year": 2014, "place": 4, "source": "https://cyclones.com/sports/wrestling/roster/kyven-gadson/1279"}, {"year": 2015, "place": 1, "source": "https://cyclones.com/sports/wrestling/roster/kyven-gadson/1279"}],

  "Trent Paulson": [{"year": 2004, "place": "qualifier", "source": "https://cyclones.com/documents/download/2025/5/14/Record_Book_25_26.pdf#page=14"}, {"year": 2005, "place": 4, "source": "https://cyclones.com/documents/download/2025/5/14/Record_Book_25_26.pdf#page=8"}, {"year": 2006, "place": 4, "source": "https://cyclones.com/documents/download/2025/5/14/Record_Book_25_26.pdf#page=8"}, {"year": 2007, "place": 1, "source": "https://cyclones.com/documents/download/2025/5/14/Record_Book_25_26.pdf#page=8"}],
  "Travis Paulson": [{"year": 2004, "place": 6, "source": "https://cyclones.com/documents/download/2025/5/14/Record_Book_25_26.pdf#page=8"}, {"year": 2005, "place": "qualifier", "source": "https://cyclones.com/documents/download/2025/5/14/Record_Book_25_26.pdf#page=14"}, {"year": 2006, "place": 6, "source": "https://cyclones.com/documents/download/2025/5/14/Record_Book_25_26.pdf#page=8"}, {"year": 2007, "place": 5, "source": "https://cyclones.com/documents/download/2025/5/14/Record_Book_25_26.pdf#page=8"}],

  "Zain Retherford": [{"year":2014,"place":5,"source":"https://gopsusports.com/news/2018/03/26/wr-zain-wins-the-hodge-again"},{"year":2016,"place":1,"source":"https://gopsusports.com/news/2018/03/26/wr-zain-wins-the-hodge-again"},{"year":2017,"place":1,"outstandingWrestler":true,"source":"https://gopsusports.com/news/2018/03/26/wr-zain-wins-the-hodge-again"},{"year":2018,"place":1,"source":"https://gopsusports.com/news/2018/03/26/wr-zain-wins-the-hodge-again"}],
  "Ed Ruth": [{"year":2011,"place":3,"source":"https://gopsusports.com/news/2011/03/19/long-and-ruth-put-penn-state-on-precipice-of-first-national-championship-since-1953"},{"year":2012,"place":1,"source":"https://gopsusports.com/news/2014/09/5/former-lion-great-ed-ruth-ready-for-world-freestyle-championships"},{"year":2013,"place":1,"source":"https://gopsusports.com/news/2014/09/5/former-lion-great-ed-ruth-ready-for-world-freestyle-championships"},{"year":2014,"place":1,"source":"https://gopsusports.com/news/2014/09/5/former-lion-great-ed-ruth-ready-for-world-freestyle-championships"}],
  "Jason Nolf": [{"year":2016,"place":2,"source":"https://gopsusports.com/news/2019/04/1/nolf-and-ogle-named-mccoy-award-winners-crow-garners-walker-award-mchugh-earns-oswald"},{"year":2017,"place":1,"source":"https://gopsusports.com/news/2019/04/1/nolf-and-ogle-named-mccoy-award-winners-crow-garners-walker-award-mchugh-earns-oswald"},{"year":2018,"place":1,"source":"https://gopsusports.com/news/2019/04/1/nolf-and-ogle-named-mccoy-award-winners-crow-garners-walker-award-mchugh-earns-oswald"},{"year":2019,"place":1,"source":"https://gopsusports.com/news/2019/04/1/nolf-and-ogle-named-mccoy-award-winners-crow-garners-walker-award-mchugh-earns-oswald"}],
  "Bo Nickal": [{"year":2016,"place":2,"source":"https://www.themat.com/news/2019/july/03/bo-nickal-is-the-2019-big-ten-male-athlete-of-the-year"},{"year":2017,"place":1,"source":"https://www.themat.com/news/2019/july/03/bo-nickal-is-the-2019-big-ten-male-athlete-of-the-year"},{"year":2018,"place":1,"outstandingWrestler":true,"source":"https://gopsusports.com/news/2019/04/1/bo-nickal-wins-the-hodge"},{"year":2019,"place":1,"source":"https://www.themat.com/news/2019/july/03/bo-nickal-is-the-2019-big-ten-male-athlete-of-the-year"}],
  'Matt McDonough': [
    { year: 2010, place: 1, source: 'https://hawkeyesports.com/sports/hof/roster/player/matt-mcdonough-hof' },
    { year: 2011, place: 2, source: 'https://hawkeyesports.com/sports/hof/roster/player/matt-mcdonough-hof' },
    { year: 2012, place: 1, source: 'https://hawkeyesports.com/sports/hof/roster/player/matt-mcdonough-hof' },
    { year: 2013, place: 'qualifier', source: 'https://s3.us-east-2.amazonaws.com/sidearm.nextgen.sites/nwca.sidearmsports.com/documents/2023/11/14/NCAA_Championship_2013.pdf#page=3' },
  ],
  'Jessman Smith': [{"year":2000,"place":"qualifier","source":"https://s3.us-east-2.amazonaws.com/sidearm.nextgen.sites/nwca.sidearmsports.com/documents/2023/11/14/NCAA_Championship_2000.pdf#page=23"},{"year":2001,"place":"qualifier","source":"https://gophersports.com/news/2001/3/16/TEN_GOLDEN_GOPHERS_EARN_ALL_AMERICA_HONORS_MINNESOTA_IN_SECOND_AT_NCAAS"},{"year":2002,"place":3,"source":"https://nwhof.org/hall_of_fame/bio/5912"},{"year":2003,"place":4,"source":"https://nwhof.org/hall_of_fame/bio/5912"}],
  'Joe Heskett': [{"year":1999,"place":3,"source":"https://cyclones.com/news/2007/10/3/1255899"},{"year":2000,"place":2,"source":"https://cyclones.com/news/2007/10/3/1255899"},{"year":2001,"place":2,"source":"https://cyclones.com/news/2007/10/3/1255899"},{"year":2002,"place":1,"source":"https://cyclones.com/news/2007/10/3/1255899"}],
  'Nate Gallick': [{"year":2003,"place":0,"source":"https://cyclones.com/documents/download/2025/5/14/Record_Book_25_26.pdf#page=14"},{"year":2004,"place":5,"source":"https://nwhof.org/hall_of_fame/bio/16013"},{"year":2005,"place":2,"source":"https://nwhof.org/hall_of_fame/bio/16013"},{"year":2006,"place":1,"source":"https://nwhof.org/hall_of_fame/bio/16013"}],
  'David Carr': [{"year":2021,"place":1,"source":"https://cyclones.com/news/2024/3/23/wrestling-david-carr-wins-second-national-title"},{"year":2022,"place":3,"source":"https://cyclones.com/news/2024/3/23/wrestling-david-carr-wins-second-national-title"},{"year":2023,"place":2,"source":"https://cyclones.com/news/2024/3/23/wrestling-david-carr-wins-second-national-title"},{"year":2024,"place":1,"source":"https://cyclones.com/news/2024/3/23/wrestling-david-carr-wins-second-national-title"}],
  'Spencer Lee': [{"year":2018,"place":1,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=71"},{"year":2019,"place":1,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=71"},{"year":2021,"place":1,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=71"},{"year":2023,"place":6,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=71"}],
  'Logan Stieber': [{"year":2012,"place":1,"source":"https://ohiostatebuckeyes.com/sports/wrestling/roster/coaches/logan-stieber/2448"},{"year":2013,"place":1,"source":"https://ohiostatebuckeyes.com/sports/wrestling/roster/coaches/logan-stieber/2448"},{"year":2014,"place":1,"source":"https://ohiostatebuckeyes.com/sports/wrestling/roster/coaches/logan-stieber/2448"},{"year":2015,"place":1,"outstandingWrestler":true,"source":"https://fs.ncaa.org/Docs/stats/wrestling_champs_records/2015-16/D1.pdf"}],
  'Jayson Ness': [{"year":2007,"place":5,"source":"https://gophersports.com/sports/wrestling/roster/jayson-ness/8031"},{"year":2008,"place":2,"source":"https://gophersports.com/sports/wrestling/roster/jayson-ness/8031"},{"year":2009,"place":3,"source":"https://gophersports.com/sports/wrestling/roster/jayson-ness/8031"},{"year":2010,"place":1,"outstandingWrestler":true,"source":"https://gophersports.com/sports/wrestling/roster/jayson-ness/8031"}],
  'Cole Konrad': [{"year":2004,"place":4,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=35"},{"year":2005,"place":2,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=35"},{"year":2006,"place":1,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=35"},{"year":2007,"place":1,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=35"}],
  'Luke Becker': [{"year":2000,"place":6,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=35"},{"year":2001,"place":4,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=35"},{"year":2002,"place":1,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=35"},{"year":2003,"place":4,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=35"}],
  'Damion Hahn': [{"year":2001,"place":5,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=35"},{"year":2002,"place":5,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=35"},{"year":2003,"place":1,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=35"},{"year":2004,"place":1,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=35"}],
  'Zach Sanders': [{"year":2009,"place":6,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=36"},{"year":2010,"place":5,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=36"},{"year":2011,"place":5,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=36"},{"year":2012,"place":3,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=36"}],
  'Dylan Ness': [{"year":2012,"place":2,"source":"https://gophersports.com/sports/wrestling/roster/dylan-ness/7874"},{"year":2013,"place":4,"source":"https://gophersports.com/sports/wrestling/roster/dylan-ness/7874"},{"year":2014,"place":2,"source":"https://gophersports.com/sports/wrestling/roster/dylan-ness/7874"},{"year":2015,"place":6,"source":"https://gophersports.com/sports/wrestling/roster/dylan-ness/7874"}],
  'Ed Banach': [{"year":1980,"place":1,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=69"},{"year":1981,"place":1,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=69"},{"year":1982,"place":2,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=69"},{"year":1983,"place":1,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=69"}],
  'Barry Davis': [{"year":1981,"place":7,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=69"},{"year":1982,"place":1,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=69"},{"year":1983,"place":1,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=69"},{"year":1985,"place":1,"outstandingWrestler":true,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=69"}],
  'Lee Fullhart': [{"year":1996,"place":4,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=70"},{"year":1997,"place":1,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=70"},{"year":1998,"place":3,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=70"},{"year":1999,"place":2,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=70"}],
  'Mark Ironside': [{"year":1995,"place":6,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=70"},{"year":1996,"place":3,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=70"},{"year":1997,"place":1,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=70"},{"year":1998,"place":1,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=70"}],
  'Duane Goldman': [{"year":1983,"place":2,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=70"},{"year":1984,"place":2,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=70"},{"year":1985,"place":2,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=70"},{"year":1986,"place":1,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=70"}],
  'Lincoln McIlravy': [{"year":1993,"place":1,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=71"},{"year":1994,"place":1,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=71"},{"year":1995,"place":2,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=71"},{"year":1997,"place":1,"outstandingWrestler":true,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=71"}],
  'Mark Perry': [{"year":2005,"place":2,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=72"},{"year":2006,"place":3,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=72"},{"year":2007,"place":1,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=72"},{"year":2008,"place":1,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=72"}],
  'Joe Williams': [{"year":1994,"place":7,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=73"},{"year":1996,"place":1,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=73"},{"year":1997,"place":1,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=73"},{"year":1998,"place":1,"outstandingWrestler":true,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=73"}],
  'Jim Zalesky': [{"year":1981,"place":5,"source":"https://nwhof.org/hall_of_fame/bio/1156"},{"year":1982,"place":1,"source":"https://nwhof.org/hall_of_fame/bio/1156"},{"year":1983,"place":1,"source":"https://nwhof.org/hall_of_fame/bio/1156"},{"year":1984,"place":1,"outstandingWrestler":true,"source":"https://nwhof.org/hall_of_fame/bio/1156"}],
  'Jeff McGinness': [{"year":1994,"place":5,"source":"https://nwhof.org/national-wrestling-hall-of-fame/champions-database?tab=ncaa&wrestler=12746"},{"year":1995,"place":1,"source":"https://nwhof.org/national-wrestling-hall-of-fame/champions-database?tab=ncaa&wrestler=12746"},{"year":1996,"place":"qualifier","source":"https://nwhof.org/brackets/66#page=6"},{"year":1998,"place":1,"source":"https://nwhof.org/national-wrestling-hall-of-fame/champions-database?tab=ncaa&wrestler=12746"}],
  'Kyle Dake': [2010,2011,2012,2013].map(year=>({year,place:1,outstandingWrestler:year===2013,source:'https://cornellbigred.com/news/2013/3/23/WREST_0323131012.aspx?path=wrest'})),
  'David Taylor': [
    {year:2011,place:2,source:'https://gopsusports.com/news/2014/04/01/david-taylor-wins-hodge-trophy-award-for-second-time'},
    {year:2012,place:1,outstandingWrestler:true,source:'https://gopsusports.com/news/2012/04/1/season-wrap-up-nittany-lion-wrestling-season-ending-notes'},
    {year:2013,place:2,source:'https://gopsusports.com/news/2014/04/01/david-taylor-wins-hodge-trophy-award-for-second-time'},
    {year:2014,place:1,outstandingWrestler:true,source:'https://www.psu.edu/news/athletics/story/nittany-lion-wrestlers-win-fourth-consecutive-national-championship'},
  ],
  'Tom Brands': [1989,1990,1991,1992].map(year=>({year,place:year===1989?4:1,outstandingWrestler:year===1992,source:'https://nwhof.org/hall_of_fame/bio_by_name/tom-brands'})),
  'Terry Brands': [
    {year:1989,place:0,source:'https://nwhof.org/brackets/59'},
    {year:1990,place:1,source:'https://nwhof.org/hall_of_fame/bio_by_name/terry-brands'},
    {year:1991,place:2,source:'https://nwhof.org/hall_of_fame/bio_by_name/terry-brands'},
    {year:1992,place:1,source:'https://nwhof.org/hall_of_fame/bio_by_name/terry-brands'},
  ],
  'Michael Moreno': [
    {year:2012,place:0,source:'https://cyclones.com/documents/download/2023/6/12/Record_Book.pdf'},
    {year:2013,place:6,source:'https://cyclones.com/news/2013/3/23/206897262'},
    {year:2014,place:5,source:'https://cyclones.com/news/2014/3/22/209441544'},
    {year:2015,place:'qualifier',source:'https://cyclones.com/news/2015/4/10/210013592'},
  ],
  'Cael Sanderson': [1999, 2000, 2001, 2002].map(year => ({year, place: 1, outstandingWrestler: true, source: 'https://cyclones.com/honors/hall-of-fame/cael-sanderson/176'})),
  'Dan Gable': [
    {year: 1968, place: 1, source: gableSource},
    {year: 1969, place: 1, outstandingWrestler: true, source: 'https://cyclones.com/documents/download/2025/5/14/Record_Book_25_26.pdf'},
    {year: 1970, place: 2, source: gableSource},
  ],
};

/** Explicit verified eligibility; never infer from a missing season. */
export const ELIGIBILITY_SEASONS: Record<string, 3 | 4> = {'Dan Gable': 3, 'Dan Hodge': 3, 'Brent Metcalf': 3, 'Vincenzo Joseph': 3};

/** Provisional anchors; interpolate between average placement point levels. */
export function placementRating(average: number): number {
  const anchors = [[0,50],[1,60],[2,70],[3,74],[4,78],[5,82],[6,86],[7,90],[9,95],[10,98]];
  for (let i = 1; i < anchors.length; i++) {
    const [x, y] = anchors[i], [px, py] = anchors[i-1];
    if (average <= x) return py + (y-py) * (Math.max(px, average)-px) / (x-px);
  }
  return 98;
}

export interface CollegeRecord { wins: number; losses: number; ties?: number; source: string; }
export const COLLEGE_RECORDS: Record<string, CollegeRecord> = {
  "Sammy Brooks": {wins:102,losses:24,source:"https://hawkeyesports.com/sports/wrestling/roster/player/sammy-brooks"},
  "Vincenzo Joseph": {wins:89,losses:9,source:"https://lehighsports.com/staff-directory/vincenzo-joseph/1277"},
  "Michael Chandler": {wins:100,losses:40,source:"https://mutigers.com/news/2013/01/17/mizzou-alum-and-mma-lightweight-champion-michael-chandler-to-defend-title-tonight"},
  "Alan Waters": {"wins": 136, "losses": 14, "source": "https://mutigers.com/sports/wrestling/roster/player/alan-waters"},
  "Mark Ellis": {"wins": 90, "losses": 39, "source": "https://mutigers.com/honors/hall-of-fame/mark-ellis/211/kiosk"},

  "J'den Cox": {"wins": 136, "losses": 5, "source": "https://mutigers.com/sports/wrestling/roster/player/jden-cox"},
  "Keegan O'Toole": {"wins": 108, "losses": 5, "source": "https://mutigers.com/sports/wrestling/roster/season/2023-24/player/keegan-otoole"},

  "Drake Houdashelt": {wins:134,losses:23,source:"https://mutigers.com/sports/wrestling/roster/player/drake-houdashelt"},
  "Brent Metcalf": {wins:108,losses:3,source:"https://hawkeyesports.com/sports/wrestling/roster/season/2009-10/player/brent-metcalf"},
  "Max Askren": {wins:104,losses:16,source:"https://mutigers.com/sports/wrestling/roster/season/2008-09/player/maxwell-askren"},
  "Nick Heflin": {wins:99,losses:28,source:"https://ohiostatebuckeyes.com/news/2014/3/25/ohio-state-athletics-good-stuff-28"},
  "Tommy Rowlands": {wins:164,losses:15,source:"https://nwhof.org/national-wrestling-hall-of-fame/champions-database?tab=ncaa&wrestler=5904"},
  "Adam Tirapelle": {wins:127,losses:21,source:"https://fightingillini.com/documents/download/2015/12/9/2015_16_Media_Guide.pdf"},
  "Yianni Diakomihalis": {wins:115,losses:2,source:"https://cornellbigred.com/aa.aspx?hid=686"},
  "John Hughes": {wins:121,losses:26,ties:2,source:"https://nwhof.org/hall_of_fame/bio/6323"},
  "Aaron Brooks": {wins:89,losses:3,source:"https://gopsusports.com/news/2024/06/17/brooks-nemeth-named-penn-state-athletes-of-the-year"},
  "Carter Starocci": {wins:104,losses:4,source:"https://gopsusports.com/news/2025/3/22/national-champion-penn-state-crowns-two-individual-titlists-to-close-out-2025-ncaa-wrestling-championships-in-philadelphia"},
  "Dan Hodge": {wins:46,losses:0,source:"https://nwhof.org/national-wrestling-hall-of-fame/bio/6"},
  "Jeff Prescott": {wins:88,losses:15,ties:2,source:"https://nwhof.org/hall_of_fame/bio/6532"},
  "Quentin Wright": {wins:116,losses:23,source:"https://gopsusports.com/news/2013/03/24/nittany-lions-win-third-straight-ncaa-wrestling-crown"},
  "Nick Lee": {wins:118,losses:13,source:"https://gopsusports.com/staff/nick-lee"},
  "Cary Kolat": {wins:111,losses:7,source:"https://navysports.com/news/2020/3/20/cary-kolat-named-navy-head-wrestling-coach.aspx?path=me"},
  "Kerry McCoy": {wins:150,losses:18,source:"https://nwhof.org/national-wrestling-hall-of-fame/bio/1272"},
  "Lou Banach": {wins:90,losses:14,ties:2,source:"https://nwhof.org/hall_of_fame/bio/93"},
  "Eric Juergens": {wins:120,losses:13,source:"https://hawkeyesports.com/news/2019/08/05/wrestling-hall-of-fame-spotlight-eric-juergens"},
  "Steve Mocco": {wins:137, losses:6, source:"https://nwhof.org/national-wrestling-hall-of-fame/bio/12557"},
  "Kenny Monday": {wins:121, losses:12, ties:2, source:"https://okstate.com/documents/download/2023/3/14/16_-_NCAA_Championships_2023.pdf#page=4"},
  "Dean Heil": {wins: 116, losses: 18, source: "https://okstate.com/documents/download/2023/3/14/16_-_NCAA_Championships_2023.pdf#page=4"},
  "Mark Branch": {"wins": 100, "losses": 18, "source": "https://okstate.com/documents/download/2015/5/18/sports_m_wrestl2013_14_release__release_20131207aaa.pdf"},
  "Mike Sheets": {"wins": 122, "losses": 12, "source": "https://okstate.com/documents/download/2015/5/18/sports_m_wrestl2013_14_release__release_20131207aaa.pdf"},

  "Johnny Thompson": {"wins": 125, "losses": 14, "source": "https://okstate.com/news/2015/11/4/WREST_1104153308"},
  "Eric Guerrero": {"wins": 117, "losses": 13, "source": "https://okstate.com/news/2009/2/27/Eric_Guerrero"},
  "Zack Esposito": {"wins": 120, "losses": 12, "source": "https://okstate.com/news/2015/11/4/WREST_1104153308"},

  "Chris Pendleton": {"wins": 118, "losses": 12, "source": "https://okstate.com/news/2015/11/4/WREST_1104153308"},
  "Jake Rosholt": {"wins": 104, "losses": 21, "source": "https://okstate.com/news/2015/11/4/WREST_1104153308"},

  "Johny Hendricks": {"wins": 126, "losses": 13, "source": "https://okstate.com/news/2013/11/14/Former_Cowboy_Johny_Hendricks_Fights_for_UFC_Welterweight_Belt"},
  "Chris Perry": {"wins": 122, "losses": 11, "source": "https://okstate.com/sports/wrestling/roster/coaches/chris-perry/2318"},

  "Alex Dieringer": {"wins": 133, "losses": 4, "source": "https://okstate.com/sports/wrestling/roster/alex-dieringer/3042"},
  "Jordan Oliver": {"wins": 127, "losses": 6, "source": "https://okstate.com/news/2015/11/9/WREST_1109152432"},
  // Prefer OSU’s 2024 official record table; older records report 154–7–2.
  "John Smith": {"wins": 152, "losses": 8, "ties": 2, "source": "https://okstate.com/documents/download/2024/3/19/OkState_NCAA_Notes.pdf#page=4"},
  "Pat Smith": {"wins": 121, "losses": 5, "ties": 2, "source": "https://nwhof.org/hall_of_fame/bio/1498"},
  "Kyle Snyder": {"wins": 75, "losses": 5, "source": "https://ohiostatebuckeyes.com/sports/wrestling/roster/kyle-snyder/2210"},
  "Jordan Burroughs": {"wins": 128, "losses": 20, "source": "https://huskers.com/sports/wrestling/roster/season/2010-11/player/jordan-burroughs"},
  "Nate Carr": {"wins": 117, "losses": 20, "ties": 1, "source": "https://sportsintegration.wvu.edu/coaches/nate-carr"},
  "Tim Krieger": {"wins": 116, "losses": 3, "ties": 2, "source": "https://cyclones.com/sports/2015/3/2/GEN_20140101173"},
  "Jake Varner": {"wins": 121, "losses": 10, "source": "https://cyclones.com/honors/hall-of-fame/jake-varner/198?path=general"},
  "Jon Reader": {"wins": 124, "losses": 23, "source": "https://cyclones.com/news/2011/3/25/205123068"},
  "Zach Roberson": {"wins": 106, "losses": 35, "source": "https://cyclones.com/staff-directory/zach-roberson/332"},
  "David Zabriskie": {"wins": 116, "losses": 22, "source": "https://cyclones.com/sports/wrestling/roster/david-zabriskie/2876"},
  "Kyven Gadson": {"wins": 90, "losses": 11, "source": "https://cyclones.com/sports/wrestling/roster/kyven-gadson/1279"},

  'Trent Paulson': {wins:117,losses:20,source:'https://nwhof.org/hall_of_fame/bio_by_name/trent-paulson'},
  'Travis Paulson': {wins:106,losses:32,source:'https://nwhof.org/news/dan-gable-museum-announces-2017-glen-brand-hof-class'},
  "Zain Retherford": {"wins":126,"losses":3,"source":"https://gopsusports.com/news/2018/03/26/wr-zain-wins-the-hodge-again"},
  "Ed Ruth": {"wins":136,"losses":3,"source":"https://gopsusports.com/news/2014/09/5/former-lion-great-ed-ruth-ready-for-world-freestyle-championships"},
  "Jason Nolf": {"wins":117,"losses":3,"source":"https://gopsusports.com/news/2019/04/1/nolf-and-ogle-named-mccoy-award-winners-crow-garners-walker-award-mchugh-earns-oswald"},
  "Bo Nickal": {"wins":120,"losses":3,"source":"https://gopsusports.com/news/2019/04/1/bo-nickal-wins-the-hodge"},
  'Matt McDonough': { wins: 122, losses: 9, source: 'https://hawkeyesports.com/sports/hof/roster/player/matt-mcdonough-hof' },
  'Joe Heskett': {"wins":143,"losses":9,"source":"https://cyclones.com/news/2007/10/3/1255899"},
  'Nate Gallick': {"wins":106,"losses":23,"source":"https://nwhof.org/hall_of_fame/bio/16013"},
  'David Carr': {"wins":120,"losses":5,"source":"https://cyclones.com/news/2024/3/23/wrestling-david-carr-wins-second-national-title"},
  'Spencer Lee': {"wins":98,"losses":6,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=71"},
  'Logan Stieber': {"wins":119,"losses":3,"source":"https://ohiostatebuckeyes.com/sports/wrestling/roster/coaches/logan-stieber/2448"},
  'Jayson Ness': {"wins":148,"losses":15,"source":"https://gophersports.com/sports/wrestling/roster/jayson-ness/8031"},
  'Cole Konrad': {"wins":155,"losses":13,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=38"},
  'Luke Becker': {"wins":126,"losses":29,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=38"},
  'Damion Hahn': {"wins":118,"losses":21,"source":"https://gophersports.com/documents/download/2023/11/28/WREST_MediaGuide2023-24.pdf#page=38"},
  'Zach Sanders': {"wins":134,"losses":27,"ties":1,"source":"https://gophersports.com/sports/wrestling/roster/zach-sanders/7997"},
  'Dylan Ness': {"wins":98,"losses":25,"source":"https://gophersports.com/sports/wrestling/roster/dylan-ness/7874"},
  'Ed Banach': {"wins":141,"losses":9,"ties":1,"source":"https://nwhof.org/hall_of_fame/bio/88"},
  'Barry Davis': {"wins":162,"losses":9,"ties":1,"source":"https://navysports.com/news/2026/4/1/navy-wrestling-assistant-coach-barry-davis-announces-his-retirement.aspx"},
  'Lee Fullhart': {"wins":107,"losses":18,"ties":0,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=70"},
  'Mark Ironside': {"wins":127,"losses":10,"ties":0,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=70"},
  'Duane Goldman': {"wins":132,"losses":10,"ties":0,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=70"},
  'Lincoln McIlravy': {"wins":96,"losses":3,"ties":0,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=71"},
  'Mark Perry': {"wins":96,"losses":16,"ties":0,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=72"},
  'Joe Williams': {"wins":129,"losses":9,"ties":0,"source":"https://storage.googleapis.com/hawkeyesports-com/2023/11/ad81eaac-2023-24-media-guide.pdf#page=73"},
  'Jim Zalesky': {"wins":131,"losses":8,"ties":1,"source":"https://nwhof.org/hall_of_fame/bio/1156"},
  'Jeff McGinness': {"wins":127,"losses":16,"ties":0,"source":"https://nwhof.org/national-wrestling-hall-of-fame/champions-database?tab=ncaa&wrestler=12746"},
  'Kyle Dake': {wins:137,losses:4,source:'https://cornellbigred.com/news/2013/3/23/WREST_0323131012.aspx?path=wrest'},
  'David Taylor': {wins:134,losses:3,source:'https://gopsusports.com/news/2014/04/01/david-taylor-wins-hodge-trophy-award-for-second-time'},
  'Tom Brands': {wins:158,losses:7,ties:2,source:'https://hawkeyesports.com/sports/wrestling/roster/season/2024-25/staff/tom-brands'},
  'Terry Brands': {wins:137,losses:7,source:'https://hof.hawkeyesports.com/inductees/terry-michael-brands/'},
  'Michael Moreno': {wins:91,losses:37,source:'https://cyclones.com/sports/wrestling/roster/michael-moreno/1333'},
  'Cael Sanderson': {wins: 159, losses: 0, source: 'https://cyclones.com/honors/hall-of-fame/cael-sanderson/176'},
};
export function recordAdjustment(record: CollegeRecord): number {
  const ties = record.ties ?? 0;
  if ([record.wins, record.losses, ties].some(v => !Number.isInteger(v) || v < 0) || record.wins + record.losses + ties === 0) throw new Error('Invalid college record');
  // Ties count as half a win. Modest adjustment: 75% is neutral, 100% adds 1.
  return 4 * ((record.wins + ties / 2) / (record.wins + record.losses + ties) - 0.75);
}
/** Owner-approved provisional tiers, applied after all bonuses and record adjustments. */
export function championshipCeiling(seasons: readonly NcaaSeason[]): number {
  const titles = Math.min(4, seasons.filter(s => s.place === 1).length);
  return 90 + titles * 2; // 0 / 1 / 2 / 3 / 4 titles: 90 / 92 / 94 / 96 / 98.
}
export function overallRating(name: string, career: CareerScore, record?: CollegeRecord): number {
  if (name === 'Dan Gable' || name === 'Cael Sanderson') return 99;
  // Owner-approved exception: Taylor's finals opposition included Kyle Dake.
  if (name === 'David Taylor') return 96;
  return Math.min(championshipCeiling(career.counted), Math.max(0, Math.round(placementRating(career.averagePlacementPoints) + career.bonusPoints + (HODGE_AWARDS[name]?.years.length ?? 0) + (record ? recordAdjustment(record) : 0))));
}
